### ISSUE TITLE
Attorney Affiliation Information

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/ETSIprototype_tm#100]
Add the affiliation drop downs to the "Add new attorney" form. We don't have the OED Canadian list yet so don't worry about inputting that information yet. The specific requirements are below if you need them. 

![affiliation information](https://user-images.githubusercontent.com/44168600/49104910-3aefd580-f24d-11e8-9503-63e81311b36e.PNG)

a)	The system shall require the user to indicate if they are either a ‘U.S. attorney in good standing’ of the bar of the highest court of a state in the United States (which includes the District of Columbia and any Commonwealth or territory of the United States) or ‘Canadian agent or attorney’ who has been granted recognition by the Director of the Office of Enrollment and Discipline.  See TMEP §602.  There should be an informational message that non-attorney trademark agents should select ’U.S. attorney in good standing’.
i)	If the user selects ‘U.S. attorney in good standing,’ then the system shall provide the user the ability to add the following “Bar membership” information:
(1)	Bar Jurisdiction (States, Territories, and Commonwealths) (Required).  
(2)	If the Bar Jurisdiction is any state, territory, or commonwealth, then the user will be able to provide the following information:
(a)	Membership #. (Optional). If user does not enter Bar Membership # then display a warning/informational message, but allow the user to proceed MSG_ID 021
(b)	Date of Admission (Required).  The date should include Month (Required), Day (Optional), and Year (Required) If no Date of Admission is provided, then display MSG_ID 022 .  
(c)	User must acknowledge the following statement: “I certify this attorney is in good standing with a bar of the highest court of any U.S. state, the District of Columbia, the U.S. commonwealths or U.S. territories” 
(3)	If No Bar Membership Jurisdiction selected or entered, then display MSG_ID 020
(4)	The system shall provide the user the ability to indicate that the Bar Jurisdiction is "Unavailable/Not Listed/Other".  
(a)	If "Unavailable/Not Listed/Other" is selected, then the user must acknowledge the following prior to proceeding: "I acknowledge that unless the attorney/agent meets the requirements of 37 C.F.R. §11.14, any power of attorney is void ab initio and the attorney/agent may not sign responses or otherwise act on behalf of the applicant in the particular trademark application.  This filing will be flagged for review by the USPTO."   
(b)	The form stylesheet and backend must flag this section of the form for further review by the examining attorney.  
(c)	If the user indicates the Jurisdiction is “Unavailable/Not Listed/Other”, the system shall also provide the user the ability to enter the name of the jurisdiction (Optional) 
ii)	If the user selects ‘Canadian agent or attorney,’ then the system shall provide the user the ability to add the following: 
(1)	Allow user to select from a list of name from the registered OED list Canadian Trademark and Patent Agents, 
(2)	If the Canadian agent or attorney is unable to locate their name, allow them to indicate ‘I can’t find my name’.  
(3)	The user shall indicate if the applicant is located in Canada.
(4)	If the attorney or owner of the mark is not located in Canada or is not on the list then provide a warning.  “Warning: Attorneys must represent applicants located in Canada.”  
(5)	Allow user to proceed through the form if there is a match on the OED list and the applicant is located in Canada.

**Comment by dutchTender** [comment]
this has image upload. will complete for the next sprint after tomorrow's demo
