### ISSUE TITLE
add https to AWS server

### ISSUE THREAD

**Issue by dutchTender** [GrantThorntonETSI/ETSIprototype_tm#15]

**Comment by dutchTender** [comment]
spring boot is set up for https, but we need configure apache. for enable port 80 amd 443 forwading on stage server

**Comment by avoreid** [comment]
Clicking on activate account launches login challenge after logging in see the profile page with a message that can't be dismissed, even by clicking on the right hand corner X, the message should also be more of a prompt maybe in green to say please complete the required fields marked with '*' in your profile to continue, as a user I have no idea which fields are required.
<img width="676" alt="incompleteprofileerror" src="https://user-images.githubusercontent.com/43755705/48206552-ade7e980-e33c-11e8-83f0-2340c109c443.PNG">

**Comment by avoreid** [comment]
Check email on registration page is cropped on the left.
<img width="670" alt="checkemail" src="https://user-images.githubusercontent.com/43755705/48206706-00c1a100-e33d-11e8-8630-4021fb1a0e06.PNG">
