### ISSUE TITLE
a message that can't be dismissed,

### ISSUE THREAD

**Issue by avoreid** [GrantThorntonETSI/ETSIprototype_tm#70]
<img width="676" alt="incompleteprofileerror" src="https://user-images.githubusercontent.com/43755705/48206552-ade7e980-e33c-11e8-83f0-2340c109c443.PNG">

_Originally posted by @avoreid in https://github.com/GrantThorntonETSI/ETSIprototype_tm/issue_comments#issuecomment-437024780_

**Comment by avoreid** [comment]
Strange text
<img width="444" alt="profilestrangetext" src="https://user-images.githubusercontent.com/43755705/48207070-dae8cc00-e33d-11e8-945b-aea0296f10bd.PNG">

**Comment by dutchTender** [comment]
i just tested this. i believe this is IE stuff, but I will work on the other items you mentioned to me. such as the email link page of the registration flow.

**Comment by dutchTender** [comment]
issue targets. fix
1. move traversal buttons up on pages that have large gaps. this is annoying for the user to move the page down to move forward.
